### ISSUE TITLE
Image server size handling.

### ISSUE THREAD

**Issue by lexpar** [ArchiveLabs/iiif.archivelab.org#12]
The IIIF image server does not appear to handle the 'size' parameter in request URIs correctly for some images. 

For instance:
1. https://iiif.archivelab.org/iiif/select00read$1/full/500,/0/default.jpg
2. https://iiif.archivelab.org/iiif/select00read$1/full/500/0/default.jpg

The first produces a 400 status code, the second produces the image at a 500 pixel width. The difference is the comma after the '500' in the URI. This is a problem, as [the first is the correct syntax](http://iiif.io/api/image/2.0/#size).

**Comment by lexpar** [comment]
This might be a pretty tricky bug, as the correct syntax works with *some* images.

ex: https://iiif.archivelab.org/iiif/musicalcurriculu00root_0$1/full/500,/0/default.jpg

**Comment by lexpar** [comment]
Has this been fixed? My exampled no longer cause a problem.

**Comment by mekarpeles** [comment]
I believe this has been resolved
