### ISSUE TITLE
Most images give errors

### ISSUE THREAD

**Issue by tristanr-cogapp** [ArchiveLabs/iiif.archivelab.org#18]
After the recent change to the ID list mentioned in https://github.com/ArchiveLabs/iiif.archivelab.org/issues/17 most identifiers will not provide a valid image, instead giving 400 or 500 responses

E.g. taking two IDs ('0----------' and '0-2aaaaaa') from https://iiif.archivelab.org/iiif gives:

http://iiif.archivelab.org/iiif/0----------/full/48,/0/default.jpg <= works fine (200 response)
http://iiif.archivelab.org/iiif/0-2aaaaaa/full/48,/0/default.jpg <= fails (400 Bad Request)

I have used different cursor values to check the first 50,000 identifiers, and of these only around 200 actually give correct responses. See below for a Python2 script that checks the first 2000 items, and which provides the following analysis:

'HTTP/1.1 400 BAD REQUEST': 1816
'HTTP/1.1 200 OK': 182, 
'HTTP/1.1 500 INTERNAL SERVER ERROR': 1
'HTTP/1.1 404 NOT FOUND': 1

Script to check:

import urllib2 as urllib
import json
import commands

ID_URL = "https://iiif.archivelab.org/iiif/?cursor=" # 1000 is max per page
IMG_URL = "http://iiif.archivelab.org/iiif/"

cursor = "" # required by Archive.org to get pages
total_statuses = {}
images = 0

for page in range(1, 3):

    print "Retrieving page {}".format(page)

    # get ID list
    response = urllib.urlopen("%s%s" % (ID_URL, cursor))
    print "getting page %s" % page
    content = response.read()
    j = json.loads(content)
    cursor = j["cursor"]

    print j["items"]
    print "got cursor: %s" % cursor

    for item in j["items"]:  # [3:]:
        images += 1
        print "retrieving image %s" % images
        id = item["identifier"]
        url = "%s%s%s" % (IMG_URL, id, "/full/48,/0/default.jpg")
        http_status = commands.getstatusoutput('curl -ILs %s | grep "HTTP/1.1"' % url)[1]
        print http_status
        if total_statuses.get(http_status):
            total_statuses[http_status] += 1
        else:
            total_statuses[http_status] = 1

print('finished. Processed %s pages and %s images' % (page, images))
print(total_statuses)

**Comment by tristanr-cogapp** [comment]
As a followup to this, I have now checked the first 250,000 IDs, and of these only 1800 return a 200 response, meaning that less than 1 in 100 requests actually results in a valid IIIF image.

@mekarpeles If it is not possible to make the API only return valid IDs, is there any way you (or anyone else!) can think of to work around this issue? E.g. starting with a cursor value that would hit a more fully populated part of the listing? Or adding additional search parameters to narrow down on a collection that does have images?

**Comment by mekarpeles** [comment]
Should be resolved
