### ISSUE TITLE
Error when installing iiify

### ISSUE THREAD

**Issue by nvanderperren** [ArchiveLabs/iiif.archivelab.org#20]
Running on mac OSX El Capitan (10.11.16), I always get this error when using the command `pip install .`

MacBook-Pro-van-Nastasia:iiif.archivelab.org nastasia$ sudo -H pip install .
Processing /Users/nastasia/iiif.archivelab.org
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-GJTjkV-build/setup.py", line 39, in <module>
        version=find_version("iiify/configs", "__init__.py"),
      File "/private/tmp/pip-GJTjkV-build/setup.py", line 35, in find_version
        raise RuntimeError("Unable to find version string.")
    RuntimeError: Unable to find version string.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-GJTjkV-build/

**Comment by mekarpeles** [comment]
Should be fixed, let me know if there are still conflicts
