### ISSUE TITLE
Objects of type 'texts' dropping the first image

### ISSUE THREAD

**Issue by narogers** [ArchiveLabs/iiif.archivelab.org#26]
In trying to integrate the Internet Archive's IIIF manifests into a custom viewer I found that it is not properly inserting the first image into manifest.json. It may be that I misunderstand the 'texts' workflow and that these things should be marked as 'images' instead. Either way here is what happens

Following the documentation (https://iiif.archivelab.org/iiif/documentation) I am pulling down http://iiif.archivelab.org/iiif/CMAMS17152/manifest.json. This particular object has two images (a front and back). However according to the manifest only the back is present. In contrast when visiting https://archive.org/details/CMAMS17152 both front and back are available for display so I know the front can be loaded. It can also be accessed directly at http://iiif.archivelab.org/iiif/CMAMS17152$0.

I've found this block in resolver.py which generates the canvases. For some reason it starts from an index of 1 instead of 0 which truncates the first image. Is this intentional behaviour or a bug?

https://github.com/ArchiveLabs/iiif.archivelab.org/blob/master/iiify/resolver.py#L153

**Comment by mekarpeles** [comment]
This may indeed be a bug will investigate today thank you!

**Comment by sammy1997** [comment]
@mekarpeles please mention a chat platform to connect to mentors of IA. I want to contribute.

**Comment by mekarpeles** [comment]
Hi @sammy1997! You can jump on chat here: https://gitter.im/ArchiveExperiments/Lobby

**Comment by mekarpeles** [comment]
This coming from Susan Lynch @ BHL (bhl biodiversity heritage library)

> We are just starting to use the IA IIIF viewer and we have a problem. IA item is https://archive.org/details/douglasshoughto00houg.  URL we are using for IIIF is https://iiif.archivelab.org/iiif/douglasshoughto00houg.  There are 10 page images.  All 10 are viewable in the regular IA book viewer and BHL but only the first 9 images are viewable in the IIIF viewer. The final page isn't there.  I checked the scandata.xml file and the final page (sequence number 10) is there.  This is correspondence/letters and the convention we're following for page metadata is date of the letter followed by implied page number within the letter.  In short, there are multiple different page 1s. The page that we need the IIIF viewer for is that page that's missing.

**Comment by pbinkley** [comment]
As someone working with enhancing IA manifests for external use, I hope this can be fixed without changing the ids of existing canvases (i.e. don't make the missing canvas 0 become canvas 1, forcing renumbering of all the others).
