### ISSUE TITLE
Coverdale Bible images

### ISSUE THREAD

**Issue by martinmueller39** [ArchiveLabs/iiif.archivelab.org#32]
Your have a pretty good image set of the first English Bible, https://archive.org/details/CoverdaleBible1535_838 Unfortunately, each page image is a double page. I wonder whether the images are splittable.  This may not be your department, but it would be worth doing. There is no provenance information about this set, but the first English Bible is the first English Bible, and it would be worth fixing it.

**Comment by hadro** [comment]
This is unfortunately not something that can be fixed in terms of the IIIF display of the images associated with this item. The manifest (https://iiif.archivelab.org/iiif/CoverdaleBible1535_838/manifest.json) already specifies the viewingHint `paged` rather than two-up, but because the underlying images have been photographed two-to-a-page there is nothing an image viewer can do to rectify this.

**Comment by martinmueller39** [comment]
Dear Josh Hadro,

I’m a little puzzled why I got cc’d on the correspondence below, since it doesn’t seem to have originated wth me or any of my colleagues.

That said, you seem to have something do with the Internet Archive’s IIIF server, and I’d like to express gratitude for the admirable clarity with which the IA has managed its access to IIIF images. In our EarlyPrint project (https://earlyprint.org) I have worked with images sources from several libraries. The IA is by far the most transparent in exposing its interface and the relevant image numbers. As for the others, transparency is not the first word that comes to mind.

With best wishes

Martin Mueller
Professor of English and Classics emeritus
Northwestern University


From: Josh Hadro ***@***.***>
Date: Thursday, March 16, 2023 at 8:17 PM
To: ArchiveLabs/iiif.archivelab.org ***@***.***>
Cc: Martin Mueller ***@***.***>, Author ***@***.***>
Subject: Re: [ArchiveLabs/iiif.archivelab.org] Coverdale Bible images (#32)

This is unfortunately not something that can be fixed in terms of the IIIF display of the images associated with this item. The manifest (https://iiif.archivelab.org/iiif/CoverdaleBible1535_838/manifest.json<https://urldefense.com/v3/__https:/iiif.archivelab.org/iiif/CoverdaleBible1535_838/manifest.json__;!!Dq0X2DkFhyF93HkjWTBQKhk!Qc4M3eOu_wv4SvfDg0ALCbb59ePJGIym7C_7v79t-yQaLwQGEV1AL5bjL1c9loeMMCY9VGaS0i5L3wkjQeeFCoGBRO83t9HE8Q$>) already specifies the viewingHint paged rather than two-up, but because the underlying images have been photographed two-to-a-page there is nothing an image viewer can do to rectify this.

**Comment by hadro** [comment]
Hi Martin,

Many thanks for your kind words, I'll pass them along to folks at the
Internet Archive more responsible than I am for the project implementation
that's proven valuable to you.

And I apologize for the message coming out of the blue -- you receive it
because you submitted a bug report here describing some issues with the
Coverdale Bible image:
https://github.com/ArchiveLabs/iiif.archivelab.org/issues/32

But thanks again for your words about the IA work, and we hope to improve
upon the existing feature set in order to make it even more useful in the
future.

Thanks and take care --

Josh

**Comment by martinmueller39** [comment]
Dear Josh,

Nothing to apologize for: now I remember dimly my “bug report”.  May I ask you a broader question? I see from Linked-In that you come out of the library world. I’m not sure whether you’re still with the IIF consortium or are now with the Internet Archive or have a foot in each.

I am one of the editors of the EarlyPrint project (https://earlyprint.org), whose ultimate ambition is the collaborative curation of the Early Modern Anglophone print heritage as it was transcribed by the Text Creation Partnership. In the background is the FREEBO initiative—making good digital images of Early Modern books freely available. IIIF is a terrific technology (I know next to nothing about its details): in principle it allows anybody to aggregate stuff from anywhere else into their own project.

So much for the theory, but the difference between practice and theory is usually larger in practice than in theory. It takes a lot of skill and tedious fiddling to break into the treasures of libraries.  Each of them has their own and not necessarily well documented protocol, and their curators spend a lot more time displaying their treasures in their own manner than letting others use them for their purposes. The Internet Archive is the single and rare exception.  I have wondered whether the international community of Early Modern scholars would be better off if the various Rare Book libraries agree to share an IIIF server at Hathi Trust. Or use the Internet Archive.

The latter is actually what many of them did in the early 2000’s.  The large majority of our current 700 “digital combos” come from texts deposited in the IA by various Rare Book libraries, mainly the Boston Public Library.  Libraries now tend to deposit copies in Hathi Trust, but Hathi has no IIIF plans.

If the various IIF installations agreed on a shared service for all the stuff that is in the English Short Title Catalogue, Early Modern scholars would probably sing a very loud Hallelujah. Is that a plausible option? Or would it be just as simple for individual libraries to pay more attention to making it a little easier for outsiders?

I would be very grateful if you have any wisdom or advice to contribute about this problem.

MM

From: Josh Hadro ***@***.***>
Date: Friday, March 17, 2023 at 11:53 AM
To: ArchiveLabs/iiif.archivelab.org ***@***.***>
Cc: Martin Mueller ***@***.***>, Author ***@***.***>
Subject: Re: [ArchiveLabs/iiif.archivelab.org] Coverdale Bible images (#32)
Hi Martin,

Many thanks for your kind words, I'll pass them along to folks at the
Internet Archive more responsible than I am for the project implementation
that's proven valuable to you.

And I apologize for the message coming out of the blue -- you receive it
because you submitted a bug report here describing some issues with the
Coverdale Bible image:
https://github.com/ArchiveLabs/iiif.archivelab.org/issues/32<https://urldefense.com/v3/__https:/github.com/ArchiveLabs/iiif.archivelab.org/issues/32__;!!Dq0X2DkFhyF93HkjWTBQKhk!WxeMQsVB4_YiJN-_woHutBPQ3fsBe84cADE4GpZiRozlUDeuTKKFe_d1Jae7Q_jYXzQbsxgQTr-Dvv4TpXnzG7jtEIs5rB2kTw$>

But thanks again for your words about the IA work, and we hope to improve
upon the existing feature set in order to make it even more useful in the
future.

Thanks and take care --

Josh
