### ISSUE TITLE
adding renderings (pdf, etc.)

### ISSUE THREAD

**Issue by eroux** [ArchiveLabs/iiif.archivelab.org#39]
It would be nice to add some [renderings](https://iiif.io/api/presentation/2.1/#rendering) in the manifest, such as the PDF export for instance. What's the method to know if it's possible to export as pdf or not?

**Comment by glenrobson** [comment]
I think this is now a duplication of https://github.com/ArchiveLabs/iiif.archivelab.org/issues/71

**Comment by eroux** [comment]
the issues are similar enough to be merged if you want, sure

**Comment by benwbrum** [comment]
Duplicate of #71
