### ISSUE TITLE
No "Access-Control-Allow-Origin" header on IIIF resources

### ISSUE THREAD

**Issue by tomcrane** [ArchiveLabs/iiif.archivelab.org#4]
Hi Mek,

Since you launched, you seem to have lost the "Access-Control-Allow-Origin" header on your IIIF resources. This means that they work in Mirador when the Mirador code is running on your domain (as in your example) but they no longer work in Mirador, Universal Viewer or any other viewer when that viewer's script is running on another domain, because the viewer is not permitted to load the info.json cross domain.

Example:

http://universalviewer.azurewebsites.net/?manifest=http://iiif.archivelab.org/platowithenglish04platuoft/manifest.json

Adding "Access-Control-Allow-Origin" with a value of "*" to your IIIF resource responses should fix this.

**Comment by mekarpeles** [comment]
Hi @tomcrane 

Thanks for the feedback! I've resolved the CORS issue and should be pushing the changes upstream in a moment.

A competing issue may be that the team recently decided we wanted to change the iiif endpoint to iiif.archivelab.org/iiif/:id -- but the url you present above should resolve correctly from iiif.archivelab.org => iiif.archivelab.org/iiif. The rational is to make it easy for developers to migrate from iiif.archivelab.org/iiif to archive.org/iiif if such a migration is decided at a future stable release.

That being said, I'm also having trouble getting the universal viewer to open the above mentioned book: http://universalviewer.azurewebsites.net/?manifest=http://iiif.archivelab.org/iiif/platowithenglish04platuoft/manifest.json -- using iiif.archivelab.org or iiif.archivelab.org/iiif.

**Comment by mekarpeles** [comment]
For what it's worth, I've confirmed on projectmirador.org I am able to open the following manuscript:

http://iiif.archivelab.org/iiif/platowithenglish04platuoft/manifest.json

**Comment by mekarpeles** [comment]
@tomcrane -- @edsilv helped me resolve this today:

"the 'manifesto' library [for UV] was missing an image profile variant. Now added:"
https://github.com/UniversalViewer/manifesto/blob/dev/src/ServiceProfile.ts#L28
