### ISSUE TITLE
Expired certificate for iiif.archivelab.org

### ISSUE THREAD

**Issue by benwbrum** [ArchiveLabs/iiif.archivelab.org#54]
It looks like the certificate for iiif.archivelab.org expired today, as an attempt to retrieve [an info.json](https://iiif.archivelab.org/iiif/Jeremiah_White_Graves_Diary_Volume_2_Book_10$0/info.json) results in 
```
NET::ERR_CERT_DATE_INVALID
Subject: iiif.archive.org

Issuer: Let's Encrypt Authority X3

Expires on: Jan 28, 2021

Current date: Jan 28, 2021
```

**Comment by mekarpeles** [comment]
You caught me mid-renewal! Give it five minutes :smile:

**Comment by benwbrum** [comment]
Verifying that the certificate is renewed.  Thanks for the quick work!
