### ISSUE TITLE
Collection manifest has incorrect context

### ISSUE THREAD

**Issue by benwbrum** [ArchiveLabs/iiif.archivelab.org#6]
The top level collection manifest at https://iiif.archivelab.org/iiif/collection.json does not pass validation at http://iiif.io/api/presentation/validator/service/validate?url=https%3A%2F%2Fiiif.archivelab.org%2Fiiif%2Fcollection.json&version=2.0&format=html as it fails with the error:
`Validation Error: Top level @context is not known`

I susppect that the context value provided needs to be changed to the presentation API instead of the image API:

``` json
  "@context":"http://iiif.io/api/image/2/context.json",
```

to

``` json
  "@context":"http://iiif.io/api/presentation/2/context.json",
```

**Comment by hadro** [comment]
Closing up, this has been fixed (though top level collection currently not working; revamp work being done on `presentation_v3` branch)
