### ISSUE TITLE
iiif.archive.org certificate expired

### ISSUE THREAD

**Issue by szmoon** [ArchiveLabs/iiif.archivelab.org#62]
It looks as though the certificate expired on Tuesday, January 25, 2022 at 5:48:38 AM PT (I noticed because I've been working with some iiif images hosted here, and now need to enable the connection for my browser while developing. )

![Screen Shot 2022-01-25 at 10 21 43 AM](https://user-images.githubusercontent.com/5179244/151036413-1ba97441-e269-4eae-b960-eb7b684c8b02.png)

**Comment by jcmundy** [comment]
I'm running into this, too.

**Comment by regisrob** [comment]
+1. Same problem here. The SSL certificate expired on Tue, 25 Jan 2022 13:48:38 GMT. So all the IIIF manifests are broken right now. 🙏

**Comment by mekarpeles** [comment]
Apologies, just renewed, thank you!

**Comment by mekarpeles** [comment]
Certbot doesn't appear to be auto-renewing, so I'm investigating

**Comment by szmoon** [comment]
@mekarpeles  Thank you so much!
