### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by garrettdashnelson** [ArchiveLabs/iiif.archivelab.org#65]
With gratitude to the volunteer time to goes into maintaining this project—just wanted to note that the server certificate expired on June 14, 2022, breaking all downstream uses of the IIIF service.

<img width="472" alt="Screen Shot 2022-06-16 at 9 20 31 AM" src="https://user-images.githubusercontent.com/2424901/174081023-38f0022e-b97d-406e-90ae-29872491824d.png">

**Comment by mekarpeles** [comment]
Certs updated! For some reason the cron has been failing and its required a manual run of `certbot` I'm seeing if I can fix the underlying problem now. Marking this issue as resolved, feel free to open if things don't seem fixed for you

**Comment by mekarpeles** [comment]
cron in place, we'll see if it succeeds, I should get an email otherwise
