### ISSUE TITLE
Baseline setup for new version of the project

### ISSUE THREAD

**Issue by digitaldogsbody** [ArchiveLabs/iiif.archivelab.org#72]
- [x] New branch
- [x] Updated Flask skeleton
- [x] Dockerfile for building with UWSGI
- [x] PyTest skeleton?

**Comment by digitaldogsbody** [comment]
Branch for development: https://github.com/ArchiveLabs/iiif.archivelab.org/tree/presentation_v3

**Comment by glenrobson** [comment]
Just noting other requirements from the notes but this could be split out into another issue:

Docker should include:
 * Nginx / Apache proxy to Flask
 * Proxy for image server 

Github actions:
 * Run tests
 * Deploy to dockerHub - to be confirmed
