### ISSUE TITLE
v3 support for A/V material

### ISSUE THREAD

**Issue by benwbrum** [ArchiveLabs/iiif.archivelab.org#77]
This issue tracks discussions about support for A/V material in the Internet Archive, which is currently not supported in v2 or the existing shim.

**Comment by saracarl** [comment]
Both audio and video items on archive.org have many different formats available. Which one should we choose for the media in the IIIF manifest?

Which one would the Internet Archive prefer we use?

Which one(s) are supported most widely by players?

**Comment by glenrobson** [comment]
I think we might be able to use the `choice` feature and provide them all. The viewer can then choose which one it can show. I was just looking at a BL audio manifest and this is they way they do it.

**Comment by saracarl** [comment]
Great idea -- can you provide a link to an example BL audio manifest, @glenrobson ?

**Comment by glenrobson** [comment]
Sure its here: https://api-beta.bl.uk/metadata/iiif/ark:/81055/vdc_100140656320.0x000002/manifest.json

note we believe the audio is IP restricted so it may not play outside the UK.

**Comment by benwbrum** [comment]
Without addressing the multi-format issue, we've created a mock-up of the audio test fixture at https://gist.github.com/benwbrum/c669baaaafab349630faf4c5bbf9deed

**Comment by benwbrum** [comment]
The current demo version of UV doesn't seem to display the canvases, but [the Aviary player](https://iiif.aviaryplatform.com/player?manifest=https://gist.githubusercontent.com/benwbrum/c669baaaafab349630faf4c5bbf9deed/raw/0733bf279e3fa744a93abe3c4e50977d297411bf/ia_av_mockup_manifest.json) displays this manifest with all of its canvases.

**Comment by glenrobson** [comment]
Item details:

https://archive.org/details/hhfbc-cyl26

and

https://archive.org/metadata/hhfbc-cyl26

**Comment by glenrobson** [comment]
Book reader link:

https://ia800202.us.archive.org/BookReader/BookReaderJSIA.php?id=hhfbc-cyl26&itemPath=/4/items/hhfbc-cyl26&server=ia800202.us.archive.org&format=jsonp&subPrefix=hhfbc-cyl26

**Comment by saracarl** [comment]
Add waveform https://archive.org/download/hhfbc-cyl26/Band%201%20Clean.png as the "AccompanyingCanvas"

Different item thumbnails of different sizes:
https://ia800202.us.archive.org/4/items/hhfbc-cyl26/FlandersFairbanks.jpg
https://ia600202.us.archive.org/4/items/hhfbc-cyl26/FlandersFairbanks_thumb.jpg

Add description metadata (see the IA item).

Add brackets in the manifest to indicate where things are coming from -- and/or use Ben's scripts logic.

Item metadata for this item:  https://archive.org/metadata/hhfbc-cyl26

**Comment by saracarl** [comment]
Handle all the audio files, but be opinionated in the order they are included in the manifest because UV only loads the first one:
MP3
FLAC
OGG
WAV

Include "rights" and "licenseURL"

**Comment by saracarl** [comment]
Here's a mock-up of the multiple thumbnails stanza to review in today's meeting:
https://gist.github.com/saracarl/9fca6c2d2c402dac6b2dd534530365bc

**Comment by glenrobson** [comment]
https://services-ia-iiif-cantaloupe-experiment.dev.archive.org/iiif/3/hhfbc-cyl26%2fBand%201%20Clean.png/info.json

**Comment by benwbrum** [comment]
Discussion: canvases should get Accompanying Canvas containing the waveforms.  (And those waveforms can be served via Canteloupe)

The item should have a thumbnail with the two ladies.

Since thumbnails can contain a list, we can just put the different images in them.

**Comment by benwbrum** [comment]
From metadata, delete Backup Location, 

Move Licenseurl elsewhere

Rights Statement is not a standard.

**Comment by benwbrum** [comment]
`licenseurl` should move to the `rights` element of th emanifest.

**Comment by benwbrum** [comment]
Delete `title` from metadata

**Comment by benwbrum** [comment]
Add a `seeAlso` block that points to the metadata API for IA.

**Comment by benwbrum** [comment]
For thumbnails, prefer the `__ia_thumb.jpg` , then `_thumb`, then the others.

**Comment by benwbrum** [comment]
Put `afpk` files in `seeAlso` for each canvas, or ignore it entirely.

**Comment by benwbrum** [comment]
- [ ] Put afpk files in seeAlso for each canvas, or ignore it entirely.
- [ ] From metadata, delete Backup Location,
- [ ] Add a seeAlso block that points to the metadata API for IA.
- [ ] licenseurl should move to the rights element of the manifest.
- [ ] Since thumbnails can contain a list, we can just put the different images in them.  (Prefer the __ia_thumb.jpg , then _thumb, then the others.)
- [ ] Add a seeAlso block that points to the metadata API for IA.
- [ ] Handle all the audio files, but be opinionated about the order.
- [ ]  Canvases should get Accompanying Canvas containing the waveforms. (And those waveforms can be served via Canteloupe)
- [ ] The item should have a thumbnail with the two ladies.

**Comment by benwbrum** [comment]
Open question -- what should we do with the spectrograms (not waveforms)?  

[ ] Put them in `seeAlso`

**Comment by saracarl** [comment]
moved.
