### ISSUE TITLE
v3 support for collections

### ISSUE THREAD

**Issue by benwbrum** [ArchiveLabs/iiif.archivelab.org#78]
The v2 shim support for collections was limited, and relied on pagination.  In v3, collections no longer support pagination; the pattern that seems to obtain is collections of sub-collections, eventually resolving to collection manifests containing only item manifests.

**Comment by benwbrum** [comment]
Say, @mekarpeles, can you explain a bit about how collections work in the Internet Archive?  I see a couple of use cases already:
* Organizational collection containing other collections https://archive.org/details/middleburycollege
* Collection containing items: https://archive.org/details/helenhartnessflanders

There may well be more, however.

**Comment by glenrobson** [comment]
Collection is a IA item. 
Items point to the collection it is in

Every collection will have at least 1 item. You can access them using the advanced search here:

https://archive.org/advancedsearch.php?q=collection%3Ainlibrary&fl[]=identifier&sort[]=&sort[]=&sort[]=&rows=50&page=1&output=json&save=yes

From https://archive.org/advancedsearch.php

**Comment by saracarl** [comment]
notes:
Archive.org collections are like a label; hierarchies emerge when a collection is a part of another collection.  A collection is an IA item.  An item will disclose what it’s collections are.  “Harry Potter book” says it’s in “collection: inLibrary”  many-to-many relationship between items and collections.  Every collection will have an item.  archive.org/details/inlibrary is a collection page archive.org/metadata/inlibrary shows the metadata for that collection (it an item!).  An item can reference any collection in it’s collection.
We can query the items in a collection using ElasticSearch/Advanced Search API.  archive.org/advancedsearch.php if you do.  
Collection:inlibrary  (in the search field) will give us json back with the # of items and the first 50 rows of items in that collection.
TODO:  how to deal with enormous collections; since IIIF v3 doesn’t support pagination.

**Comment by glenrobson** [comment]
Note IIIF discussion on large collections: https://github.com/IIIF/api/issues/2174

**Comment by glenrobson** [comment]
Dynamic search prototype: https://github.com/ArchiveLabs/iiif.archivelab.org/blob/master/iiify/app.py#L60-L65

**Comment by hadro** [comment]
Here's an example of an IA collection we can test with, all CC0 items: https://archive.org/details/frankbford

**Comment by benwbrum** [comment]
I've done a bit more playing around with collections, and have some observations:
* Collections in the Internet Archive are *very large*.  The example Josh found has more than 7000 items.  The example audio manifest we've been working belongs to four collections, the smallest of which is still more than 1000 items.
* I'm not sure that we'll be able to fetch thumbnails for collection items without hitting the metadata API for each item.  How important are they?

**Comment by benwbrum** [comment]
I've taken a pass at creating a collection from the Helen Harkness Ballad Collection (the smallest collection attached to the item we used for the A/V manifest), and the results are here: https://gist.githubusercontent.com/benwbrum/8793dd032c3d292e47d2c5c520441064/raw/ab173715f7333161b1cd74371413be7349b47ddb/collection.json

Notes:
* This item is so big that the validator is still running after a few minutes.  We'll need some way of avoiding this.
* The collection label is not returned (as far as I can tell) in the advanced search query used to find the items.  I had to get that from https://archive.org/metadata/helenhartnessflanders
* I did a simplistic query for the identifier, title, and description of items in the collection matching the ID.  If we decide to filter on size, we might need to do a quick search and look at the response header for the number of items.  My query is https://archive.org/advancedsearch.php?q=collection%3Dhelenhartnessflanders&fl%5B%5D=description&fl%5B%5D=identifier&fl%5B%5D=title&sort%5B%5D=&sort%5B%5D=&sort%5B%5D=&rows=2000&page=1&output=json&callback=callback&save=yes

**Comment by hbromley** [comment]
> * I'm not sure that we'll be able to fetch thumbnails for collection items without hitting the metadata API for each item.  How important are they?

Do you need to fetch the actual thumbnail images, or can you just embed an `<img>` link for them? If the latter is sufficient, you can do as archive.org collection pages (and search-result pages) do, and rely on the image service: represent each item via `<img src="https://archive.org/services/img/{item identifier}">`, as in https://archive.org/services/img/HHFBC_fbc.pf.f06.179p; no need to hit up the MDAPI for each item.

> * The collection label is not returned (as far as I can tell) in the advanced search query used to find the items.

I'm not sure what's meant by "collection label" here, but pretty much all metadata should be available in search results. Do you mean you want the search results to show what collections each item is in? Or do indicate whether or not each item is itself a collection? Something else?

> * If we decide to filter on size, we might need to do a quick search and look at the response header for the number of items.

Does "filter on size" mean include/exclude collections in search results sets based on the number of items they contain? If so, you can use the `item_count` field in the search doc. For example, you can see that the `helenhartnessflanders` collection satisfies this search query (>1000 items):

https://archive.org/advancedsearch.php?q=identifier%3Ahelenhartnessflanders+AND+item_count%3A[1000+TO+*]&fl[]=identifier&fl[]=item_count&output=json

but not this one (<1000 items):

https://archive.org/advancedsearch.php?q=identifier%3Ahelenhartnessflanders+AND+item_count%3A[*+TO+1000]&fl[]=identifier&fl[]=item_count&output=json

**Comment by benwbrum** [comment]
> Do you need to fetch the actual thumbnail images, or can you just embed an <img> link for them?

An image reference should be fine, so that link might just be perfect -- thanks!

> I'm not sure what's meant by "collection label" here, but pretty much all metadata should be available in search results. Do you mean you want the search results to show what collections each item is in?

A collection like [this](https://archive.org/details/frankbford) has an identifier, `frankbford` and a title, `Frank B. Ford: Collected Publications and Manuscripts`.  From the identifier, we're trying to construct a IIIF collection that lists all the items along with the title and description of the collection.  So far as I can tell, [the Advanced Search Query](https://archive.org/advancedsearch.php?q=collection%3Afrankbford&fl%5B%5D=description&fl%5B%5D=identifier&fl%5B%5D=title&sort%5B%5D=&sort%5B%5D=&sort%5B%5D=&rows=50&page=1&output=json) for the items does not also return the title/description of the collection itself, so we will need to also hit [the metadata API for the collection identifier](https://archive.org/metadata/frankbford) if we want to include those in our IIIF collection responses.

> Does "filter on size" mean include/exclude collections in search results sets based on the number of items they contain?

This is a question for other IIIF folks, but my temptation is to hide the existence of collections with more than `n` items from the IIIF implementation, since we won't be able to deliver them in a single `Collection` document.  That would mean not linking to them from any top-level collection listing, not linking to them from item manifests, and possibly more.

**Comment by hbromley** [comment]
> [the Advanced Search Query](https://archive.org/advancedsearch.php?q=collection%3Afrankbford&fl%5B%5D=description&fl%5B%5D=identifier&fl%5B%5D=title&sort%5B%5D=&sort%5B%5D=&sort%5B%5D=&rows=50&page=1&output=json) for the items does not also return the title/description of the collection itself, so we will need to also hit [the metadata API for the collection identifier](https://archive.org/metadata/frankbford) if we want to include those in our IIIF collection responses.

Ah, I see. If you'd like the results of the search query to include the collection itself, along with all its members, you could [add `OR identifier:frankbford` to the query](https://archive.org/advancedsearch.php?q=collection%3Afrankbford+OR+identifier%3Afrankbford&fl[]=description&fl[]=identifier&fl[]=title&fl[]=mediatype&rows=50&output=json).

**Comment by benwbrum** [comment]
We discussed this in the meeting today, and came up with the following plan:
* Collection manifests will be rendered with pagination, so that the `items` element will include 50 items of `"type": "Manifest`, followed by zero to two items of `"type": "Collection"` linking to the previous and next page.
* Since we'll be able to render collections of any size this way, there will be no need to filter out large collections.  As a result, any manifest may contain links to all collections containing it.
* Rendering the `label` for a collection often requires hitting the `metadata` endpoint; this will add a single query per page, which isn't too bad.

**Comment by glenrobson** [comment]
Paging only supported through 10,000 results:

https://archive.org/advancedsearch.php?q=collection%3Ainlibrary&fl[]=identifier&fl[]=mediatype&fl[]=title&sort[]=&sort[]=&sort[]=&rows=500&page=9077&output=json&save=yes

To find max:

10,000 / number of results per page (500) = 20 pages max

Page 20 works:

https://archive.org/advancedsearch.php?q=collection%3Ainlibrary&fl[]=identifier&fl[]=mediatype&fl[]=title&sort[]=&sort[]=&sort[]=&rows=500&page=20&output=json&save=yes

But not page 21:

https://archive.org/advancedsearch.php?q=collection%3Ainlibrary&fl[]=identifier&fl[]=mediatype&fl[]=title&sort[]=&sort[]=&sort[]=&rows=500&page=21&output=json&save=yes

**Comment by glenrobson** [comment]
You can ask for all 10k in one go:

https://archive.org/advancedsearch.php?q=collection%3Ainlibrary&fl[]=identifier&fl[]=mediatype&fl[]=title&sort[]=&sort[]=&sort[]=&rows=10000&page=1&output=json&save=yes

but maybe better to ask for 1k 10 times:

https://archive.org/advancedsearch.php?q=collection%3Ainlibrary&fl[]=identifier&fl[]=mediatype&fl[]=title&sort[]=&sort[]=&sort[]=&rows=1000&page=1&output=json&save=yes

**Comment by glenrobson** [comment]
I've added the linked list collection. Example here:

https://gist.github.com/glenrobson/82bdadadb55e6d854385bddb12feda49

Pull request:

https://github.com/ArchiveLabs/iiif.archivelab.org/pull/106

**Comment by glenrobson** [comment]
add types for collection and manifests.

**Comment by glenrobson** [comment]
Re-order so its label at the top.

**Comment by glenrobson** [comment]
Add description as summary.
