### ISSUE TITLE
v3 support for A/V captions as annotations

### ISSUE THREAD

**Issue by benwbrum** [ArchiveLabs/iiif.archivelab.org#79]
If captions or transcripts are available for A/V material in the Internet Archive, manifests should expose them as annotations so that players can display them.

**Comment by benwbrum** [comment]
Question for @mekarpeles -- do caption files actually exist?

**Comment by hadro** [comment]
Yes, at least some do, per this post: https://blog.archive.org/2018/03/07/archive-video-now-supports-webvtt-for-captions/
And we can add some fixtures to #73

**Comment by saracarl** [comment]
moved.
