### ISSUE TITLE
Archive.org "text" versus "images"

### ISSUE THREAD

**Issue by mekarpeles** [ArchiveLabs/iiif.archivelab.org#8]
@regisrob brings up a great and valid point that the (Internet) Archive has engineered some special rules to negotiate / map between archive.org items and IIIF manifests. As a result, we're discovering some types of edge case archive.org items break when accessed via their IIIF API, e.g:

https://iiif.archivelab.org/iiif/MS246a

Here's why! The Internet Archive's IIIF server acknowledges (works with) 2 types of archive.org item format types -- "images" and "texts".

Items of type "images" may actually contain multiple image files which all map to the same IIIF id. A consequence of this is we only have a good way to address the 1st image file in the item's file collection. This obviously presents a problem (which should be opened as a separate issue) because it makes it hard to address exact files we want to address within an "images" type item. We've explored addressing this by having something like `itemid`$`filename` as the IIIF id (i.e. appending some delimiter and `filename` to the resource id).

This strategy is similar to how we already treat "texts" items. A "texts" type resource has many pages (many images associated with the item). The way we handle this with archive.org's IIIF server is by adding a $ delimiter to the item's IIIF id and then allowing the user to specify a page number to get to the resource: e.g. http://iiif.archivelab.org/iiif/tayloreuclid00euclrich$2 retrieves the second page of Euclid's elements book "texts" and can be manipulated using the IIIF API, whereas http://iiif.archivelab.org/iiif/tayloreuclid00euclrich will simply open the manifest for the entire book in mirador and cannot be directly manipulated as an item. So that's "images", their edge case challenge, and a proposed solution. But that's not the issue we're experiencing in the case of id MS246a.

The other type of IIIF item the Archive considers is "texts" which means a _very_ specific thing, i.e. works scanned, processed, and derived using/conforming to our official texts workflow. As mentioned above, we handle this by using a $ delimiter and a page number to address each specific page of a "texts" manuscript as a unique IIIF item.

In the case of item MS246a, this has a type "texts" but is misclassified according to our (the Archive's) definition because it is actually an item containing a bunch of image files.  This specific item (i.e. the one with id `MS246a` -- see https://archive.org/details/MS246a) is an archive.org item which contains many (~800) image files. It's a case of semantic departure (what is a text to our user versus what is a text to our infrastructure). The solution for this is, we'll have to convert it to a type of "images". I'm cc'ing @jjjake, my colleague at the Internet Archive, who can review this with the collections team (hopefully in time for your Tuesday presentation).

If it's helpful, a summary is: (1) there is a critical problem with "images" format items which contain multiple image files (it's only possible to address a single image file for the item) and (2) there is an implicit, not strictly enforced assumption / requirement that "texts" format refers to a very specific archive.org item which has been scanned, processed, and derived through our scanning workflow.

And again, all of this is an artifact of @aeschylus and I having to work around how archive.org is programmed.

**Comment by wumpus** [comment]
Jake just left for vacation.

**Comment by mekarpeles** [comment]
No problem, I can look into it

**Comment by regisrob** [comment]
@mekarpeles thank you for ticketing this so quickly and diligently

**Comment by mekarpeles** [comment]
@regisrob this may not be done in time for your talk tomorrow -- may I suggest another text from that collection which has been derived correctly? Most items in the collection https://archive.org/details/bibliothequesaintegenevieve should work.

Unless there's a specific reason you're showcasing La Cité de Dieu, traduction de "Raoul de Praelles". https://archive.org/details/MS246a (it is a pretty beautiful book!)

**Comment by regisrob** [comment]
Thanks @mekarpeles, that's very kind of you. Unfortunately we had a specific reason to showcase this particular manuscript (Ms246a), but it is not a blocker for our talk (we have other examples from the BnF).

**Comment by hadro** [comment]
Closing this up, the item in question has been update to type "texts" and more generally these distinctions will be handled with more fine-grained logic in the rewrite underway on the `presentation_v3` branch
