### ISSUE TITLE
support for OCR text as annotations (v3/v2)

### ISSUE THREAD

**Issue by benwbrum** [ArchiveLabs/iiif.archivelab.org#80]
OCR text created by the derivation process can be exposed as annotations for books and image-based media, enabling presentation and consumption of the text by IIIF clients.

**Comment by benwbrum** [comment]
v2 mock-up (see the second page)
* [Manifest](https://gist.github.com/benwbrum/e7e2fb9962a6aaba2cc0d6ae8f1b6d98)
* [Annotation List](https://gist.github.com/benwbrum/e82bb493e495dd16d06213440dfcd675)

**Comment by hadro** [comment]
Notes from: 2023-08-17
@mekarpeles proposal: may want to port over the OCR archive lab into this manifest service / app
Code is contained here: https://github.com/ArchiveLabs/api.archivelab.org/blob/master/server/api/archive.py#L240-L268

**Comment by digitaldogsbody** [comment]
In the annotation list mockup, I think the type should be `dctypes:Text` rather than `cnt:ContentAsText`

**Comment by hadro** [comment]
Context needed for textgranularity extension use of "page"

**Comment by hadro** [comment]
Decision to embed annotation lists to reduce potential number of requests on clients

**Comment by benwbrum** [comment]
Mek adds these resources to the AL APIs which should probably be incorporated into production:

* https://github.com/archiveLabs/api.archivelab.org
* https://github.com/ArchiveLabs/api.archivelab.org/blob/master/server/api/archive.py#L240-L268

**Comment by benwbrum** [comment]
Q: Where should the `@context` live in the manifest, now that we've embedded the annotation pages within the manifest?

A: At the top of the manifest, along with the IIIF presentation API context.  NB: the IIIF presentation API `@context` statement should be last, since it overrides other values.

Q: Should these plaintext representations of a page of text be in a `rendering` element within the canvas, or in an annotation targeting the full canvas?

A: Philosophically speaking, `rendering` is probably better.  However, from a UI perspective, viewers are likely to present it to the user as a downloadable link (as one would with a PDF file).  That behavior is probably not desired for some OCR -- for example when a user cannot read Fraktur typefaces, and wants to read the text of the page alongside the facsimile.

Current plan is to implement it in one direction and test in viewers.

**Comment by benwbrum** [comment]
Notes from today's call:
We should place the text granularity context after the IIIF presentation context in the v2 manifest, but before it in the v3 manifest.

**Comment by saracarl** [comment]
When we drop this manifest:
https://gist.githubusercontent.com/benwbrum/e7e2fb9962a6aaba2cc0d6ae8f1b6d98/raw/df2598dd8a67ef941c2e03fa07dbe9485f736a9c/ia_ocr_annotation_mockup_v2.json
Into Mirador, the annotations don't show up.  

Here's how the OCR text annotation is modeled in the manifest:
```
"otherContent": [
   {
      "@id": "https://iiif.archivelab.org/iiif/rbmsbk_ap2-v4_2001_V55N4$9/ocr",
      "@type": "sc:AnnotationList",
      "label": "OCR Text",
      "resources": [
         {
            "@type": "oa:Annotation",
            "motivation": "sc:painting",
            "textGranularity": "page",
            "on": "https://iiif.archivelab.org/iiif/books/rbmsbk_ap2-v4_2001_V55N4$9/canvas",
            "resource": {
               "@id": "https://api.archivelab.org/books/rbmsbk_ap2-v4_2001_V55N4/pages/9/plaintext",
               "@type": "dctypes:Text",
               "format": "text/plain"
            }
         }
      ]
   }
]
```

Any idea why not?

**Comment by glenrobson** [comment]
This is Johannes OCR viewer: https://mirador-textoverlay.netlify.app/

**Comment by saracarl** [comment]
The gist is a v2 manifest; therefore the annotations need to be "seeAlso" or "rendering" (more correctly rendering, but seeAlso is likely better supported.)

The annotation seems right for v3; at least it matches the recipe.  Where to test??  Maybe  Johannes' mirador that takes hOCR or Alto would show it?  Or perhaps it won't because it's just text?

**Comment by glenrobson** [comment]
As mentioned I think this is syntacticlly correct and matches the recipe:

https://iiif.io/api/cookbook/recipe/0068-newspaper/

but in v2 its probably seeAlso or rendering

**Comment by saracarl** [comment]
moved.
