### ISSUE TITLE
Auth workflow for "borrowable"/lending items

### ISSUE THREAD

**Issue by saracarl** [ArchiveLabs/iiif.archivelab.org#90]
This is a place for our ideas & details / how to handle the auth/book borrowing workflow.

**Comment by digitaldogsbody** [comment]
Using IIIF Auth you can point the viewer to where to get the cookie, and then as long as it is set for the image server domain - then the clients should send it with the AJAX requests for tiles etc

**Comment by benwbrum** [comment]
Covered in #88
