### ISSUE TITLE
Canvas Ids - to migrate or not?

### ISSUE THREAD

**Issue by glenrobson** [ArchiveLabs/iiif.archivelab.org#92]
Canvas Ids currently look as follows ([from this manifest](https://iiif.archivelab.org/iiif/b29000427_0001/manifest.json)):

 * [https://iiif.archivelab.org/iiif/b29000427_0001$0/canvas](https://iiif.archivelab.org/iiif/b29000427_0001$0/canvas)
 * [https://iiif.archivelab.org/iiif/b29000427_0001$1/canvas](https://iiif.archivelab.org/iiif/b29000427_0001$1/canvas)
 * [https://iiif.archivelab.org/iiif/b29000427_0001$2/canvas](https://iiif.archivelab.org/iiif/b29000427_0001$2/canvas)
 * [https://iiif.archivelab.org/iiif/b29000427_0001$3/canvas](https://iiif.archivelab.org/iiif/b29000427_0001$3/canvas)

etc. 

## Case for keeping them:
If we are migrating to version 3 we should retain the canvas identifiers because:

 * Most IIIF annotations point to the canvas identifier and this will mean people's annotations still work.  

## Case for changing 

 * We are going to be using iiif.archive.org for other identifiers and it will look strange if we have one archivelab identifier.

**Comment by glenrobson** [comment]
Suggestion we add a iiif/legacy/<identifier>/manifest.json option to be able to get access to the old manifests with old identifiers (particularly canvas).

Include seeAlso in both old and new.

**Comment by benwbrum** [comment]
Canvas IDs are the same in the production version.
