### ISSUE TITLE
Should thumbnails be based on `__ia_thumb.jpg` or another image?

### ISSUE THREAD

**Issue by saracarl** [ArchiveLabs/iiif.archivelab.org#97]
I think we need to have a discussion about thumbnails in manifests for IA items.

I had originally thought we'd do an array of thumbnails; for this item:
https://ia800202.us.archive.org/4/items/hhfbc-cyl26/
We'd use these images for thumbnails:
[FlandersFairbanks.jpg](https://ia800202.us.archive.org/4/items/hhfbc-cyl26/FlandersFairbanks.jpg)
[FlandersFairbanks_thumb.jpg](https://ia800202.us.archive.org/4/items/hhfbc-cyl26/FlandersFairbanks_thumb.jpg)                        
[__ia_thumb.jpg](https://ia800202.us.archive.org/4/items/hhfbc-cyl26/__ia_thumb.jpg)
(If we did that, what order would be best to put them in, given that some viewers will likely take the first one?  Largest to smallest?)

Then @pwallace suggested we use `__ia_thumb.jpg`, as it's the actual Internet Archive thumbnail, but the actual `__ia_thumb.jpg` is pretty small (137x180), and therefore not really iiif-y.  That being said, we probably could support it, but until #94 is fixed, we won't be sure what options are available and how they look. 

And then trying to mock this up for the AV manifest, I discovered that the recommendation is to include more-or-less the entire info.json in the service block for the thumbnail:

> Multiple methods exist for describing a thumbnail in your manifest. For a Manifest, it makes most sense to use a full-size image URI in conjunction with a IIIF Image Service containing the whole IIIF Image service JSON. Clients consuming a Manifest thumbnail will have unpredictable size requirements; reproducing the complete service JSON gives them the most flexibility and best shot at quickly and efficiently displaying your object’s thumbnail.

Perhaps we should revisit the idea of using `__ia_thumb.jpg` in favor of a more standard image that could be sized by the viewer?

If we use `__ia_thumb.jpg`, I don't think we should include the whole service block.  This is how we've mocked up the service block in the AV manifest.

**Comment by digitaldogsbody** [comment]
https://services-ia-iiif-cantaloupe-experiment.dev.archive.org/iiif/3/hhfbc-cyl26%2f__ia_thumb.jpg/full/max/0/default.jpg

**Comment by hadro** [comment]
And it does work in v2 as well, just for giggles: https://services-ia-iiif-cantaloupe-experiment.dev.archive.org/iiif/2/hhfbc-cyl26%2f__ia_thumb.jpg/full/full/0/default.jpg (though as Mike points out we should indeed be using 3)

**Comment by benwbrum** [comment]
We think that the correct implementation is one of the following two:

## Cantaloupe-based service
* Find the file with the type `JPEG Thumb`, look at its `original` attribute to get the file it was derived from (which may be large)
* Include the original image with a link to it on Cantaloupe and embed the `info.json` service block.

## Static service
* Find the file with the type `JPEG Thumb`.
* Serve that file through the IA's `download` link instead of Cantaloupe.

**Comment by hadro** [comment]
@glenrobson and I discussed this today, and unfortunately we don't have dimensions easily available for most of these images in the files metadata, which means to add the service we would have to query the info.json first, which seems like a lot of overhead for limited return.

As a result, I think we'll start with the static service for thumbnails, and we can revisit if/when we need service for some reason.

**Comment by glenrobson** [comment]
We went with the cantaloupe option.
