### ISSUE TITLE
include "uploaded by" user in item manifest?

### ISSUE THREAD

**Issue by saracarl** [ArchiveLabs/iiif.archivelab.org#98]
Do we need to include any information about the uploading user on an item's manifest?  

I noticed that Middlebury, who uploaded (and presumably digitized) this item:
https://archive.org/details/hhfbc-cyl26

Is only mentioned in our manifest in 2 places:  the summary and the rights statement.

By contrast, the IA page for the item implies a bit more of the Middlebury (authority?  provenance?) with these bits:

![image](https://user-images.githubusercontent.com/708566/236567840-f594121e-35c1-4d3a-b898-27a76887596b.png)

The "uploaded by" links to the user profile of the userID that uploaded the material:
https://archive.org/details/@mdyill

I think this is worth discussing.

**Comment by hadro** [comment]
I feel like that makes sense -- in this particular case, seems like it would make sense to include them in addition to IA in the `provider` block:
https://iiif.io/api/presentation/3.0/#provider

But would that always be the case? Is there enough machine readable metadata about the provider to consistently add them in there?

**Comment by benwbrum** [comment]
During today's discussion, we determined that the data available is insufficient to identify a holding institution.  It just so happens that our audio fixture has a really nice UploadedBy page, but this seems like an aberration.
